version: "3.7"
services:
  php-fpm:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php_fpm
    build:
      context: ./.docker/php
    env_file:
      - .env
    user: 1001:1001
    environment:
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/app:rw
      - ./tests/reports:/tests/reports/:rw
    working_dir: /app
