version: "3.7"
services:
  php-fpm:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php_fpm
    build:
      context: ./.docker/php
    env_file:
      - .env
    user: 1000:1000
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/app:rw
    working_dir: /app
