name: phpunit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker-compose up -d
   
    - name: Composer Install
      run: composer install -vvv
    
    - name: Phpunit
      run: docker-compose run --rm --no-deps php-fpm sh -lc 'php ./vendor/phpunit/phpunit/phpunit -c ./phpunit.xml --testdox --stderr --coverage-clover=coverage.xml'

    - name: Send code coverage report to Codecov.io
      uses: codecov/codecov-action@v2
      with:
        #files: $GITHUB_WORKSPACE/tests/reports/clover.xml
        token: ${{ secrets.CODECOV_TOKEN }}
